version: '3.8'

services:
  elasticsearch:
    build:
      context: gateway2/docker-elk-new/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./gateway2/docker-elk-new/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - my_network

  logstash:
    build:
      context: gateway2/docker-elk-new/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./gateway2/docker-elk-new/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./gateway2/docker-elk-new/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    expose: [5000]

    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - my_network

    depends_on:
      - elasticsearch

  kibana:
    build:
      context: gateway2/docker-elk-new/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./gateway2/docker-elk-new/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - my_network
    depends_on:
      - elasticsearch

  redis:
    container_name: redis
    command: --port 6380
    image: "redis:alpine"
    restart: always
    ports:
      - 6380:6380
    expose: [6380]
    environment:
      - REDIS_URL=redis://cache
    networks:
      - my_network
  

  cache-master:
    build: ./cache-master
    container_name: pbl-cache-master
    tty: true
    volumes: 
      - ./cache-master:/cache-master
    restart: always
    ports:
      - 6666:6666
    networks:
      - my_network

  cache-slave1-replica1:
    build: ./cache-slave
    container_name: pbl-cache-slave1-replica1
    tty: true
    volumes: 
      - ./cache-slave:/cache-slave
    restart: always
    depends_on: [cache-master]
    environment:
      - SLAVE_NAME=slave1
    # command: bash -c "mix local.hex --force && mix deps.get && iex -S mix"
    
    networks:
      - my_network

  cache-slave1-replica2:
    build: ./cache-slave
    container_name: pbl-cache-slave1-replica2
    tty: true
    volumes: 
      - ./cache-slave:/cache-slave
    restart: always
    depends_on: [cache-master]
    environment:
      - SLAVE_NAME=slave1
    # command: bash -c "mix local.hex --force && mix deps.get && iex -S mix"
    
    networks:
      - my_network

  cache-slave2-replica1:
    build: ./cache-slave
    container_name: pbl-cache-slave2-replica1
    tty: true
    volumes: 
      - ./cache-slave:/cache-slave
    restart: always
    depends_on: [cache-master]
    environment:
      - SLAVE_NAME=slave2
    # command: bash -c "mix local.hex --force && mix deps.get && iex -S mix"
    networks:
      - my_network


  flask-gateway:
    # image: flask-gateway:latest
    build: ./gateway2

    container_name: gateway2
    environment:
      - FLASK_ENV=development
      - GATEWAY_PORT=5003
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - CUSTOM_CACHE_HOST=cache-master
      - CUSTOM_CACHE_PORT=6666
      - USE_LOGGER=True
    ports:
      - 5003:5003
    expose: [5003]
    # wait some seconds for for elk stack then run gateway
    command: bash -c "sleep 5 && python -u app.py"

    depends_on:
      - redis
      - elasticsearch
      - logstash
      - kibana
    networks:
      - my_network

  service-stub-t1:
    container_name: service-stub-t1
    build: ./service-stub-t1
    environment:
      SERVICE_MY_ADDRESS: http://service-stub-t1:8000
      GATEWAY_ADDRESS: http://flask-gateway:5003
    ports:
      - 8000:8000
    expose: [8000]
    command: bash -c "sleep 15 && python -u service_type1.py"
    depends_on:
      - flask-gateway
    networks:
      - my_network


  service-stub-t2:
    container_name: service-stub-t2
    build: ./service-stub-t2
    environment:
      SERVICE_MY_ADDRESS: http://service-stub-t2:8001
      GATEWAY_ADDRESS: http://flask-gateway:5003
    ports:
      - 8001:8001
    expose: [8001]
    command: bash -c "sleep 16 && python -u service_type2.py"
    depends_on:
      - flask-gateway
    networks:
      - my_network


networks:
  my_network:
    driver: bridge

volumes:
  elasticsearch:
